# Generated by Django 5.1.4 on 2025-01-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_applicant_customuser_is_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_applicant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_recruiter',
            field=models.BooleanField(default=True),
        ),
    ]
