# Generated by Django 5.1.4 on 2025-01-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_is_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
