# Generated by Django 5.1.4 on 2025-01-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_company',
            field=models.BooleanField(default=False),
        ),
    ]
