# Generated by Django 5.1.4 on 2025-01-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_has_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_resume',
            field=models.BooleanField(default=False),
        ),
    ]
